workflows:
  flutter_webview_app:
    name: Flutter WebView App
    max_build_duration: 60
    environment:
      groups:
        - base # 包含 PGYER_UKEY 和 PGYER_API_KEY
      flutter: stable
      xcode: latest
      cocoapods: default

      # 使用自动代码签名
      ios_signing:
        #distribution_type: ad_hoc
        #bundle_identifier: com.ccgametest.live
        provisioning_profiles:
          - cc_game_prod_profile
        certificates:
          - cc_game_prod_cer

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Check Flutter environment
        script: |
          flutter doctor -v

      # Android 构建
      - name: Build Android APK
        script: |
          flutter build apk --no-tree-shake-icons --split-per-abi

      # iOS 构建
      - name: Build iOS IPA
        script: |
          echo "构建 iOS IPA..."
          flutter build ipa --obfuscate --split-debug-info=../build_output --export-method ad-hoc

    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - xs121913958@163.com

      scripts:
        - name: Upload to Pgyer
          script: |
            # 上传 Android APK
            for apk in $(find build/app/outputs/flutter-apk -name "*.apk"); do
              echo "上传 Android APK: $apk 到蒲公英..."
              curl -F "file=@$apk" \
                   -F "uKey=$PGYER_UKEY" \
                   -F "_api_key=$PGYER_API_KEY" \
                   https://www.pgyer.com/apiv2/app/upload
              echo ""
            done

            # 上传 iOS IPA
            IPA_PATH="$CM_BUILD_DIR/build/ios/ipa/Runner.ipa"
            if [ -f "$IPA_PATH" ]; then
              echo "上传 iOS IPA 到蒲公英..."
              curl -F "file=@$IPA_PATH" \
                   -F "uKey=$PGYER_UKEY" \
                   -F "_api_key=$PGYER_API_KEY" \
                   https://www.pgyer.com/apiv2/app/upload
            else
              echo "警告: 未找到 IPA 文件 $IPA_PATH"
              # 尝试查找任何 IPA 文件
              find $CM_BUILD_DIR -name "*.ipa" -exec echo "找到IPA文件: {}" \;
            fi