workflows:
  # Flutter构建流水线
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: for_codemagic
    environment:
      # android签名信息
      android_signing:
        - cc_game_apk_jks
      # ios签名信息
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.ccgametest.live
      vars:
        PACKAGE_NAME: "com.ccgametest.live"
        # 自定义应用名称
        APP_NAME: "CC GAME 1"
        # 自定义待加载的 web 网址
        WEB_URL: "https://reimagined-memory-jjgwj4xwqgxrfq4p4-8080.app.github.dev"
        # 自定义待加载的极光推送的 JPUSH_APP_KEY
        JPUSH_APP_KEY: "8b68b9303424eadca9e99ae9"

      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # android. 配置local.properties
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      # ios. 设置签名
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      # 获取Flutter依赖
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      # flutter：更新应用名称
      - name: Update app name
        script: |
          echo "Updating app name..."
          dart run rename_app:main all="${APP_NAME}"

      # flutter：更新用户图标，此步骤需先在flutter项目中更新图标资源文件后才能应用新图标
      - name: Update app icons
        script: |
          echo "Update icons..."
          dart run flutter_launcher_icons

      # flutter：更新启动图资源，此步骤需先在flutter项目中更新启动页资源文件后才能应用新的启动图
      - name: Update splash screen
        script: |
          echo "Updating splash screen..."
          dart run flutter_native_splash:create --path=./flutter_native_splash.yaml

      # flutter：更新项目 webUrl.dart 文件中的内容
      - name: Update WEB endpoint
        script: |
          echo "Update webUrl.dart..."
          sed -i '' \
              -e "s#const String webUrl = \".*\";#const String webUrl = \"${WEB_URL}\";#" \
              -e "s#const String jpushAppKey = \".*\";#const String jpushAppKey = \"${JPUSH_APP_KEY}\";#" \
              lib/webUrl.dart
          echo "Verifying updated variables..."
          grep -nE "webUrl|jpushAppKey" lib/webUrl.dart

      # android. 打包安卓apk
      - name: Build apk with Flutter
        script: |
          flutter build apk --no-tree-shake-icons --split-per-abi

      # ios. 安装 Pods
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      # ios. 构建ipa
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - xs121913958@163.com
        notify:
          success: true
          failure: false