workflows:
  flutter_webview_app:
    name: Flutter WebView App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        EXPORT_METHOD: "development"
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches

    scripts:
      - name: Install dependencies
        script: flutter pub get

      # Android 构建
      - name: Build Android APK
        script: |
          flutter build apk --no-tree-shake-icons --split-per-abi

      # iOS 构建 - 使用 flutter build ipa（推荐）
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-tree-shake-icons --export-method $EXPORT_METHOD --no-codesign
          mkdir -p build/ios/ipa
          # 重命名以便后续使用
          cp build/ios/ipa/*.ipa build/ios/ipa/Runner-unsigned.ipa 2>/dev/null || true

    artifacts:
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - xs121913958@163.com

      scripts:
        - name: Upload to Pgyer
          script: |
            # 上传 Android APK
            if [ -f "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" ]; then
              curl -F "file=@build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" \
                   -F "uKey=$PGYER_UKEY" \
                   -F "_api_key=$PGYER_API_KEY" \
                   https://www.pgyer.com/apiv2/app/upload
            fi
            
            # 上传 iOS IPA
            if [ -f "build/ios/ipa/Runner.ipa" ]; then
              curl -F "file=@build/ios/ipa/Runner.ipa" \
                   -F "uKey=$PGYER_UKEY" \
                   -F "_api_key=$PGYER_API_KEY" \
                   https://www.pgyer.com/apiv2/app/upload
            elif [ -f "build/ios/ipa/Runner-unsigned.ipa" ]; then
              curl -F "file=@build/ios/ipa/Runner-unsigned.ipa" \
                   -F "uKey=$PGYER_UKEY" \
                   -F "_api_key=$PGYER_API_KEY" \
                   https://www.pgyer.com/apiv2/app/upload
            fi