workflows:
  flutter_webview_app:
    name: Flutter WebView App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      # 添加环境变量
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        XCODE_CONFIGURATION: "Release"

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches

    scripts:
      - name: Install dependencies
        script: flutter pub get

      # 添加 Flutter 医生检查
      - name: Check Flutter environment
        script: flutter doctor -v

      # Android 构建
      - name: Build Android APK
        script: |
          flutter build apk --no-tree-shake-icons --split-per-abi

      - name: Install CocoaPods dependencies
        script: |
          echo "使用pod deintegrate清除ios依赖缓存，再使用pod install重新安装ios依赖"
          cd ios && pod deintegrate && pod install && cd ..

      # iOS 构建 - 改进版本
      - name: Build iOS IPA
        script: |
          # 确保输出目录存在
          mkdir -p build/ios/archive
          mkdir -p build/ios/ipa
          
          # 清理之前的构建
          xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration "$XCODE_CONFIGURATION"
          
          # 构建 iOS app
          echo "开始构建 iOS 应用..."
          flutter build ios --release --no-tree-shake-icons --no-codesign
          
          # 使用 xcodebuild 生成 xcarchive
          echo "开始归档..."
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration "$XCODE_CONFIGURATION" \
            -sdk iphoneos \
            -archivePath build/ios/archive/Runner.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive | xcpretty
          
          # 检查归档是否成功
          if [ ! -d "build/ios/archive/Runner.xcarchive" ]; then
            echo "错误: 归档失败，未找到 Runner.xcarchive"
            exit 1
          fi
          
          # 导出 IPA
          echo "开始导出 IPA..."
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: Verify IPA
        script: |
          echo "检查构建产物..."
          ls -la build/ios/ipa/ || true
          ls -la build/ios/archive/ || true

    artifacts:
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - xs121913958@163.com

      scripts:
        - name: Upload to Pgyer
          script: |
            # 上传 Android APK
            if [ -f "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" ]; then
              echo "上传 Android APK 到蒲公英..."
              curl -F "file=@build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" \
                   -F "uKey=$PGYER_UKEY" \
                   -F "_api_key=$PGYER_API_KEY" \
                   https://www.pgyer.com/apiv2/app/upload
            fi
            
            # 上传 iOS IPA
            if [ -f "build/ios/ipa/Runner.ipa" ]; then
              echo "上传 iOS IPA 到蒲公英..."
              curl -F "file=@build/ios/ipa/Runner.ipa" \
                   -F "uKey=$PGYER_UKEY" \
                   -F "_api_key=$PGYER_API_KEY" \
                   https://www.pgyer.com/apiv2/app/upload
            elif [ -f "build/ios/ipa/Runner-unsigned.ipa" ]; then
              echo "上传未签名的 iOS IPA 到蒲公英..."
              curl -F "file=@build/ios/ipa/Runner-unsigned.ipa" \
                   -F "uKey=$PGYER_UKEY" \
                   -F "_api_key=$PGYER_API_KEY" \
                   https://www.pgyer.com/apiv2/app/upload
            else
              echo "警告: 未找到可上传的 IPA 文件"
              ls -la build/ios/ipa/ || true
            fi