workflows:
  flutter_webview_app:
    name: Flutter WebView App
    max_build_duration: 60
    environment:
      groups:
        - base # 确保在此组中设置了 PGYER_UKEY 和 PGYER_API_KEY
      flutter: stable
      xcode: latest
      cocoapods: default

      # iOS 代码签名配置
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.ccgametest.live

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Check Flutter environment
        script: flutter doctor -v

      # 关键修复：确保代码签名设置正确应用
      - name: Set up code signing
        script: |
          echo "设置代码签名..."
          # 确保使用正确的 bundle identifier
          plutil -replace CFBundleIdentifier -string "com.ccgametest.live" ios/Runner/Info.plist
          # 显示当前配置，用于调试
          echo "当前bundle identifier:"
          plutil -extract CFBundleIdentifier xml1 -o - ios/Runner/Info.plist
          # 应用代码签名设置
          xcode-project use-profiles

      # Android 构建
      - name: Build Android APK
        script: |
          flutter build apk --no-tree-shake-icons --split-per-abi

      # 创建导出选项文件
      - name: Create export options plist
        script: |
          cat > export_options.plist <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>teamID</key>
            <string>X9A9C8FGQ6</string>
            <key>compileBitcode</key>
            <false/>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
          </dict>
          </plist>
          EOL
          echo "导出选项文件内容:"
          cat export_options.plist

      # iOS 构建
      - name: Build iOS IPA
        script: |
          echo "开始构建 iOS IPA..."
          # 检查代码签名设置
          echo "检查代码签名设置..."
          xcodebuild -showBuildSettings -workspace ios/Runner.xcworkspace -scheme Runner
          
          # 构建 IPA
          flutter build ipa --release --no-tree-shake-icons \
            --export-options-plist $CM_BUILD_DIR/export_options.plist
          
          # 检查输出
          echo "构建完成，检查输出目录:"
          ls -la $CM_BUILD_DIR/build/ios/ipa/ || echo "IPA目录不存在"

    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - xs121913958@163.com

      scripts:
        - name: Upload to Pgyer
          script: |
            # 上传 Android APK
            for apk in $(find build/app/outputs/flutter-apk -name "*.apk"); do
              echo "上传 Android APK: $apk 到蒲公英..."
              curl -F "file=@$apk" \
                   -F "uKey=$PGYER_UKEY" \
                   -F "_api_key=$PGYER_API_KEY" \
                   https://www.pgyer.com/apiv2/app/upload
              echo ""
            done

            # 上传 iOS IPA
            IPA_PATH="$CM_BUILD_DIR/build/ios/ipa/Runner.ipa"
            if [ -f "$IPA_PATH" ]; then
              echo "上传 iOS IPA 到蒲公英..."
              curl -F "file=@$IPA_PATH" \
                   -F "uKey=$PGYER_UKEY" \
                   -F "_api_key=$PGYER_API_KEY" \
                   https://www.pgyer.com/apiv2/app/upload
            else
              echo "警告: 未找到 IPA 文件 $IPA_PATH"
              # 尝试查找任何 IPA 文件
              find $CM_BUILD_DIR -name "*.ipa" -exec echo "找到IPA文件: {}" \;
            fi