workflows:
  flutter_webview_app:
    name: Flutter WebView App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      # android: latest
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches

    scripts:
      - name: Install dependencies
        script: flutter pub get

      # 生成 keystore 文件
      - name: Prepare Keystore
        script: |
          mkdir -p android/app
          echo $KEYSTORE_BASE64 | base64 --decode > release.jks

      # Android 构建 - 已签名 APK
      - name: Build Android APK (Signed)
        script: |
          # 创建 keystore.properties
          echo "storeFile=android/app/release.jks" > android/keystore.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> android/keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> android/keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/keystore.properties
          
          # 构建已签名 APK
          flutter build apk --no-tree-shake-icons --split-per-abi

      # iOS 构建 - 未签名 IPA
      - name: Build iOS (Unsigned IPA for Super Sign)
        script: |
          flutter build ios --release --no-tree-shake-icons --no-codesign
          mkdir -p build/ios/ipa
          xcrun -sdk iphoneos PackageApplication \
            -v build/ios/iphoneos/Runner.app \
            -o $(pwd)/build/ios/ipa/Runner-unsigned.ipa

    artifacts:
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - xs121913958@163.com

      scripts:
        - name: Upload Android APK to Pgyer
          script: |
            curl -F "file=@build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" \
                 -F "uKey=$PGYER_UKEY" \
                 -F "_api_key=$PGYER_API_KEY" \
                 https://www.pgyer.com/apiv2/app/upload

        - name: Upload iOS IPA to Pgyer
          script: |
            curl -F "file=@build/ios/ipa/Runner-unsigned.ipa" \
                 -F "uKey=$PGYER_UKEY" \
                 -F "_api_key=$PGYER_API_KEY" \
                 https://www.pgyer.com/apiv2/app/upload
